pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

import "../services"

/**
 * Themes — the theme catalogue and the Matugen bridge.
 *
 * A theme is little more than a seed colour: `apply()` runs Matugen, turns the
 * seed (or, for the dynamic `wallpaper` theme, the current wallpaper image) into
 * a Material 3 colour scheme, and writes it into `Colors.qml`, which re-themes
 * the whole island.
 *
 * The same Matugen run also renders the templates in `~/.config/matugen`, which
 * theme kitty and Hyprland; their post-hooks reload each app. No `--dry-run`, in
 * other words — the JSON on stdout is still what feeds `Colors.qml`.
 *
 * The `colors` / `bg` fields on each entry are six preview swatches and a card
 * background. They are generated from the same seed, so a card previews the
 * palette you actually get. The wallpaper card's swatches are refreshed every
 * time Matugen runs.
 *
 * The chosen id is persisted to the shell state directory and restored on
 * startup by `restore()` (called from shell.qml).
 *
 * NOTE: the root is an `Item`, not a `QtObject`, so the `Process` / `FileView`
 * / `Connections` children below can be declared through the default `data`
 * property. It is never shown — it only hosts the Matugen bridge.
 */
Item {
    id: root

    property var catalog: [
        // Dynamic: Matugen reads the colours out of the current wallpaper.
        { id: "wallpaper", name: "Wallpaper", seed: "", type: "scheme-tonal-spot",
          dynamic: true,
          colors: ["#3a3a44", "#4a4a58", "#5c5c6e", "#7a7a8e", "#9a9aac", "#c0c0d0"],
          bg: "#1a1a1c" },

        // Static: Catppuccin Mocha (mauve seed), with Mocha's own accents as the
        // preview swatches and `base` as the card background.
        { id: "catppuccin", name: "Catppuccin", seed: "#cba6f7", type: "scheme-tonal-spot",
          colors: ["#cba6f7", "#89b4fa", "#94e2d5", "#a6e3a1", "#f9e2af", "#f38ba8"],
          bg: "#1e1e2e" },

        // Static: Everforest Hard (green seed), with the palette's accents as
        // the preview swatches and `bg0` (#333c43) as the card background.
        { id: "everforest-hard", name: "Everforest Hard", seed: "#a7c080", type: "scheme-tonal-spot",
          colors: ["#a7c080", "#7fbbb3", "#83c092", "#dbbc7f", "#e69875", "#e67e80"],
          bg: "#333c43" }
    ]

    /// Read-only view for the carousel.
    readonly property var themes: catalog

    /// Card highlighted in the carousel (selection, not necessarily applied).
    property int current: 0
    /// Id of the last theme that actually applied. Drives the "applied" marker.
    property string appliedId: ""
    /// Id currently being generated by Matugen.
    property string pendingId: ""
    /// True while Matugen is running.
    property bool busy: false
    /// Human-readable hint / error shown under the carousel.
    property string status: ""

    function themeById(id) {
        for (var i = 0; i < catalog.length; i++)
            if (catalog[i].id === id)
                return catalog[i]
        return null
    }

    function indexOf(id) {
        for (var i = 0; i < catalog.length; i++)
            if (catalog[i].id === id)
                return i
        return 0
    }

    /// Move the highlight without applying.
    function select(index) {
        if (index >= 0 && index < catalog.length)
            current = index
    }

    /// Generate (via Matugen) and apply the theme with the given id.
    function apply(id) {
        var target = themeById(id)
        if (!target)
            return

        var command
        if (target.dynamic) {
            if (!Wallpaper.currentPath) {
                pendingId = id
                if (!Wallpaper.loaded) {
                    status = "Scanning for wallpapers…"
                    Wallpaper.rescan()
                } else {
                    status = "No wallpaper found — add one in the Wallpapers tab"
                }
                return
            }
            command = ["matugen", "image", Wallpaper.currentPath,
                       "--mode", "dark", "--json", "hex",
                       "--prefer", "saturation", "--fallback-color", "#7aa2f7"]
        } else {
            command = ["matugen", "color", "hex", target.seed,
                       "--mode", "dark", "--json", "hex",
                       "--type", target.type || "scheme-tonal-spot"]
        }

        pendingId = id
        status = ""
        busy = true
        matugen.command = command
        matugen.running = false
        matugen.running = true
    }

    function applyCurrent() {
        if (catalog.length > 0)
            apply(catalog[current].id)
    }

    Process {
        id: matugen

        stdout: StdioCollector {
            id: matugenOut
            waitForEnd: true
            onStreamFinished: root.handleOutput(matugenOut.text)
        }

        onExited: root.busy = false
    }

    function handleOutput(text) {
        var id = pendingId
        pendingId = ""
        busy = false

        if (!id)
            return
        if (!text || text.length === 0) {
            status = "Matugen produced no colours — is it installed?"
            return
        }

        try {
            var data = JSON.parse(text)
            if (!data || !data.colors)
                throw new Error("missing colours")

            Colors.applyMatugen(data.colors, "dark")
            appliedId = id
            current = indexOf(id)
            updatePreview(id, data)
            persist(id)
            status = ""
        } catch (e) {
            status = "Could not read Matugen output"
        }
    }

    /// Refresh a card's preview swatches from a freshly generated scheme. The
    /// wallpaper card changes whenever the wallpaper does.
    function updatePreview(id, data) {
        var target = themeById(id)
        if (!target)
            return

        function tone(family, level) {
            var f = data.palettes ? data.palettes[family] : null
            return (f && f[String(level)]) ? f[String(level)].color : ""
        }

        var dots = [
            tone("primary", 40), tone("primary", 60), tone("primary", 80),
            tone("secondary", 70), tone("tertiary", 70), tone("error", 70)
        ]
        if (dots.every(function (d) { return d.length > 0 }))
            target.colors = dots
        if (data.colors.surface_container && data.colors.surface_container.dark)
            target.bg = data.colors.surface_container.dark.color

        // Reassign so the carousel's model binding notices the change.
        catalog = catalog.slice()
    }

    // ── Persistence ──────────────────────────────────────────────────────────
    FileView {
        id: stateFile
        path: Quickshell.statePath("theme")
        blockLoading: true
        blockWrites: false
        printErrors: false
    }

    function persist(id) {
        try { stateFile.setText(id) } catch (e) { /* best effort */ }
    }

    /// Restore the theme chosen in a previous session, if any. The saved id may
    /// name a theme that no longer exists (the catalogue changed), so fall back
    /// to the first available theme rather than leaving the palette untouched.
    function restore() {
        var saved = ""
        try { saved = String(stateFile.text()).trim() } catch (e) { saved = "" }
        if (saved.length > 0 && themeById(saved))
            apply(saved)
        else if (catalog.length > 0)
            apply(catalog[0].id)
    }

    // When the wallpaper changes while the wallpaper theme is in use (or while
    // it is waiting for a wallpaper to appear), regenerate from the new image.
    Connections {
        target: Wallpaper
        function onCurrentPathChanged() {
            if (root.appliedId === "wallpaper" || root.pendingId === "wallpaper")
                root.apply("wallpaper")
        }
    }
}
